@files = (
	['//project/propertySheet/property[propertyName="ec_setup"]/value', 'ec_setup.pl'],
	['//project/procedure[procedureName="openSupportTicket"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'procedures/openSupportTicket/form.xml'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="getVersion"]/command', 'procedures/openSupportTicket/steps/getVersion.pl'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="createTicket"]/command', 'procedures/openSupportTicket/steps/createTicket.sh'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="grabDestinationDir"]/command', 'procedures/openSupportTicket/steps/grabDestinationDir.pl'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="createTicketDirectory"]/command', 'procedures/openSupportTicket/steps/createTicketDirectory.sh'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="grabCommander.log"]/command', 'procedures/openSupportTicket/steps/grabCommander.log.sh'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="grabService.log copy"]/command', 'procedures/openSupportTicket/steps/grabService.log copy.sh'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="collectTimeBasedLogs"]/command', 'procedures/openSupportTicket/steps/collectTimeBasedLogs.pl'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="collectJobIdBasedLogs"]/command', 'procedures/openSupportTicket/steps/collectJobIdBasedLogs.pl'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="collectAgentLogs"]/command', 'procedures/openSupportTicket/steps/collectAgentLogs.pl'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="listing"]/command', 'procedures/openSupportTicket/steps/listing.pl'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="createBundle"]/command', 'procedures/openSupportTicket/steps/createBundle.sh'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="uploadBundleToSharefile"]/command', 'procedures/openSupportTicket/steps/uploadBundleToSharefile.sh'],
	['//project/procedure[procedureName="openSupportTicket"]/step[stepName="commentForFiles"]/command', 'procedures/openSupportTicket/steps/commentForFiles.sh'],
);
